kind: pipeline
name: ci
steps:
- commands:
  - sudo chown -R makepkg .
  - make check
  image: reg.dist.svc.cluster.znet:5000/zachfi/aur-build-image
  name: build
  pull: always
trigger:
  branch:
  - main
